# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title: Lionel's Blog
email: lion6396643@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
# 一個後端工程師，這裡是我的學習紀錄以及講屁話的地方~~
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lionel223.github.io"
tagline: 'A Jekyll theme'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.1.0
